// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: getMangaDetails.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getMangaDetails = `-- name: GetMangaDetails :many
SELECT 
    m.id AS manga_id,
    m.title AS manga_title,
    m.original_language,
    m.status,
    t.title AS alternate_title,
    a.name AS author_name,
    ar.name AS artist_name
FROM 
    manga m
LEFT JOIN titles t ON m.id = t.manga_id
LEFT JOIN manga_authors ma ON m.id = ma.manga_id
LEFT JOIN authors a ON ma.author_id = a.id
LEFT JOIN manga_artists mar ON m.id = mar.manga_id
LEFT JOIN artists ar ON mar.artist_id = ar.id
ORDER BY 
    m.title, t.language_code, a.name, ar.name
`

type GetMangaDetailsRow struct {
	MangaID          uuid.UUID
	MangaTitle       sql.NullString
	OriginalLanguage sql.NullString
	Status           sql.NullString
	AlternateTitle   sql.NullString
	AuthorName       sql.NullString
	ArtistName       sql.NullString
}

func (q *Queries) GetMangaDetails(ctx context.Context) ([]GetMangaDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMangaDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMangaDetailsRow
	for rows.Next() {
		var i GetMangaDetailsRow
		if err := rows.Scan(
			&i.MangaID,
			&i.MangaTitle,
			&i.OriginalLanguage,
			&i.Status,
			&i.AlternateTitle,
			&i.AuthorName,
			&i.ArtistName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
